### ISSUE TITLE
Package 'php5-dev' has no installation candidate

### ISSUE THREAD

**Issue by wsdo** [stesie/docker-v8js#1]

**Comment by several27** [comment]
That https://github.com/stesie/docker-v8js/pull/2 should fix most of the issues related to the old versions of php, python, and missing wget. However, it still doesn't fix the issue of missing libv8_platform.a file, that I am not sure how to solve.

```
ar: /usr/local/src/v8/out/native/obj.target/tools/gyp/libv8_libplatform.a: No such file or directory
```

**Comment by stesie** [comment]
ehh, sorry, haven't noticed this issue ... and yes, it's broken due to the base image upgrading from Ubuntu 14.04 (Trusty) to Ubuntu 16.04 (Xenial).  Thanks @several27 for fixing this.
